/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Converter para Celsius ou Fahrenheit? (C/F)");
        String tipo = scanner.next().toUpperCase();

        System.out.print("Digite a temperatura:");
        double temperatura = scanner.nextDouble();

        Conversor tempConverter = new Conversor();
        tempConverter.setTipo(tipo);
        tempConverter.setTemperatura(temperatura);

        System.out.print("Resultado: " + tempConverter.calcular());
        System.out.println(tempConverter.getTipo() + "°");
    }
}